# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-14 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_image', models.ImageField(upload_to='image/')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
